main:
    access_key: "DGN57sdflXC4x5AmT5Q9e0xl7D0fyxSMWjF4um8+aFR3OTLsEE6eZA=="
    music_path: "/home/pi/FAM/music"
    groq_api_key: "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"
    openai_api_key: "sk-proj-K8hfsSF9vbG1ccu7Mo50T3BlbkFJXB6nXSORFrhYVjkzTWaR"
    model_name: "llama3-70b-8192"
    eleven_labs_api_key: "sk_d75e31d1462f955bca620c90ebf6de3d1dfe8ad2921c88ce"
    serpapi_api_key: "48a885db2fcd95e6972fc0d2610bd2be32d626d208621182a0a3a1255d122bf6"
utilities:
    author: "AKSHAT SINGH KUSHWAHA"
    audio_files:
        success: "/home/pi/FAM//assets/audio/success.mp3"
        error: "/home/pi/FAM//assets/audio/error.mp3"
        load: "/home/pi/FAM//assets/audio/load.mp3"
    model_path: "/home/pi/FAM//model/vosk-model-small-en-in-0.4"
    weather_api_key: "054b217266c57c45c2c6dca381babd9f"
    news_api_key: "67971eebe05d4dffaed478cf1560f4cd"
    email:
        sender_email: "fam.assistant01@gmail.com"
        sender_password: "vfrq hbgg hqvh yfse"
        smtp_server: "smtp.gmail.com"
        smtp_port: 587
    image_path: "/home/pi/FAM//assets/image.jpg"
music_search:
    output_path: "/home/pi/FAM//music"
spotify:
    client_id: "a89a6ccfc0a14b669d150062f8caeb86"
    client_secret: "8746a164bb3946c9b3353a3c822b09b9"
